[pytest]
testpaths = tests
pythonpath = .
addopts = -ra --strict-markers --cov=app --cov-report=term-missing --cov-report=xml
filterwarnings =
    ignore:Type google\._upb\._message.*:DeprecationWarning
    ignore:datetime\.datetime\.utcnow.*:DeprecationWarning
    ignore:LegacyAPIWarning:sqlalchemy.exc.SAWarning
